const style = {
    container: {
        paddingBottom: '1em',
        display: 'block',
    },
    subWrapper: {
        height: '2.5em',
        backgroundColor: '#fafafa',
        width: '97%',
        borderWidth: '1px',
        borderRadius: '8px',
        padding: '0.5em',
        justifyContent: 'space-between',
        marginTop: '0.25em',
    },
    titleTypo: {
        color: '#333333',
        fontSize: '1.28571em',
        fontWeight: 'bold',
        lineHeight: '1em',
        marginBlockStart: '0.83em',
        marginBlockEnd: '0.83em',
        display: 'block',
        fontFamily: 'sans-serif',
    },
    radioWrapper: {
        height: 'auto',
        backgroundColor: '#fafafa',
        width: '97%',
        borderWidth: '1px',
        borderRadius: '8px',
        padding: '1.15em',
        marginTop: '0.25em',
    },
    img: {
        marginRight: '10px',
        display: 'flex',
        alignSelf: 'center',
        width: '50px',
        height: '50px',
    },
    hr: {
        height: '1px',
        width: '100%',
        backgroundColor: 'black',
    },
    bankingText: {
        textAlign: 'center',
        whiteSpace: 'pre-line',
        paddingLeft: '2em',
        paddingRight: '2em',
        color: '#737373',
        fontSize: '14px',
    },
    orText: {
        textAlign: 'center',
        whiteSpace: 'pre-line',
        paddingLeft: '2em',
        paddingRight: '2em',
        color: '#737373',
        fontSize: '14px',
        fontWeight: 'bold',
        marginTop: '1.2em',
    },
    methodSpace: {
        width: '50%',
        marginTop: '1.2em',
        alignSelf: 'center',
    },
    footerWrapper: { width: '100%', position: 'relative', marginTop: '2rem' },
    link: {
        textDecoration: 'none',
        color: '#338dbc',
        transition: 'color 0.2s ease-in-out',
        display: 'inline-block',
        cursor: 'pointer',
        fontSize: '14px',
        fontFamily: 'sans-serif',
        lineHeight: '1.5em',
        marginLeft: '1.2em',
    },
};

export default style;
