const style = {
    boxWrapper: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
        width: 'auto',
        height: 'auto',
        borderRadius: '15px',
        p: 3,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'column',
        background: '#14182f',
        color: '#fff',
    },
    title: {
        display: 'flex',
        justifyContent: 'flex-end',
        position: 'absolute',
        marginBottom: '10px',
    },
    btn: {
        width: 'auto',
        borderRadius: '20px',
        backgroundColor: '#18608a',
        color: '#ffffff',
        fontSize: '13px',
        fontWeight: 'bold',
        letterSpacing: '1px',
        textTransform: 'none',
    },
    childWrapper: {
        marginTop: '15px',
        display: 'flex',
        justifyContent: 'flex-end',
        flexDirection: 'row',
    },
};
export default style;
